# Generated by Django 5.2.13 on 2026-04-14 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="chat",
            name="model",
            field=models.CharField(default="openai/gpt-oss-120b:free", max_length=128),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="default_model",
            field=models.CharField(default="openai/gpt-oss-120b:free", max_length=128),
        ),
    ]
