# Generated by Django 5.2.13 on 2026-04-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_message_images_alter_chat_model_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="about_me",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="birth_date",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="gender",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
