# Generated by Django 5.2.13 on 2026-04-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_usersettings_about_me_usersettings_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="gender",
            field=models.CharField(
                choices=[
                    ("none", "Not set"),
                    ("male", "Мужской"),
                    ("female", "Женский"),
                ],
                default="none",
                max_length=16,
            ),
        ),
    ]
