# Generated by Django 5.2.13 on 2026-04-14 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_usersettings_birth_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="about_me",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="gender",
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=150)),
                ("bio", models.TextField(blank=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Мужской"),
                            ("female", "Женский"),
                            ("other", "Другой"),
                            ("not_specified", "Не указан"),
                        ],
                        default="not_specified",
                        max_length=20,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("avatar_color", models.CharField(default="#006950", max_length=20)),
                ("avatar_emoji", models.CharField(default="😀", max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
