# Generated by Django 5.2.13 on 2026-04-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_usersettings_about_me_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="avatar_color",
            field=models.CharField(blank=True, default="#006950", max_length=32),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="avatar_emoji",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
