# Generated by Django 5.2.13 on 2026-04-16 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_usersettings_avatar_color_usersettings_avatar_emoji_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="notifications_enabled",
        ),
    ]
