# Generated by Django 5.2.13 on 2026-04-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_usersettings_notifications_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="model",
            field=models.CharField(
                default="nvidia/nemotron-3-nano-30b-a3b:free", max_length=128
            ),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="default_model",
            field=models.CharField(
                default="nvidia/nemotron-3-nano-30b-a3b:free", max_length=128
            ),
        ),
    ]
